### ISSUE TITLE
快速登录接口不能使用

### ISSUE THREAD

**Issue by lrbmike** [LancerComet/bilibili-minilogin-node#1]
你好
最近发现B站的快速登录接口已经不能正常登录返回cookie
接口返回 {"status":false,"message":{"code":-105}}

希望看看能不能进行修复
谢谢

**Comment by LancerComet** [comment]
因为 B 站快速登陆加了验证码 Σ(ﾟдﾟ;)
因为种种原因近期可能不会处理  还请见谅 _(:3」∠)_
